### ISSUE TITLE
CraftingRequest: 41: Can't find craftable item fingerprint minecraft:glass:0:null

### ISSUE THREAD

**Issue by Rasmun** [sidoh/stockpile#7]
Hi again.  I setup a stocked item for Glass, but apparently didn't have enough sand to create the requested 10,000 Glass.  After a while, the below error showed up in the computer and the program terminated.  I can't completely confirm this, but it seemed like other stocked items should have also been created during this time, but they were ignored it seems (not totally sure).

Anyway, I thought I read somewhere that you intended this to just patiently wait until it could craft the item, not fail if a component was missing.  Unfortunately, I wasn't able to consistently duplicate this, so there may be other factors I am not aware of.

![2016-10-04 08_25_41-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/14100145/19080813/288febbe-8a0d-11e6-9edb-0ade860ee5b0.png)

Thanks again for such a great program!

**Comment by Rasmun** [comment]
Note:  Now that I have enough sand, it is working correctly.

**Comment by sidoh** [comment]
Sounds like it's the same as #1. Do you know if you replaced the interface, cabling, power went out to the AE network, you removed/replaced your sand recipe, etc.?

Definitely shouldn't happen, but I'm not sure what's causing it. I've been running stockpile on my own server for weeks without noticing this.

If you suspect it's due to not having all ingredients (kinda sounds that way), I can try to replicate.

**Comment by Rasmun** [comment]
I was playing with it a lot, so I did remove/add the recipe at one point.  I am going to put some time into testing this to give you a better idea what is going on.  I'll let you know.

**Comment by Rasmun** [comment]
I have tried several times now and I can't reproduce it.  Very odd...  I guess you can close this and I'll add a new one or add to #1 if I find more about it.

**Comment by sidoh** [comment]
:+1: sounds good. I'm sure it's some weird edge case / race condition. Thanks for trying to reproduce it. Definitely let me know if you notice it again. :)
